### ISSUE TITLE
Get RuntimeException in updateDeviceToken method

### ISSUE THREAD

**Issue by arsalanNasiri** [chabok-io/chabok-client-android#6]
``` java
AdpPushClient.java line 4220
com.adpdigital.push.AdpPushClient.updateDeviceToken

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:355)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)`

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.adpdigital.push.Callback.onFailure(java.lang.Throwable)' on a null object reference
       at com.adpdigital.push.AdpPushClient.updateDeviceToken(AdpPushClient.java:4220)
       at com.adpdigital.push.AdpPushClient.updateDeviceToken(AdpPushClient.java:4195)
       at com.adpdigital.push.AdpPushClient.access$1700(AdpPushClient.java:101)
       at com.adpdigital.push.MRR.doInBackground(MRR.java:1631)
       at com.adpdigital.push.MRR.doInBackground(MRR.java:1553)
       at android.os.AsyncTask$2.call(AsyncTask.java:334)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)
```

**Comment by Husseinhj** [comment]
<p dir="rtl">این مشکل در نسخه <a href="https://doc.chabok.io/android/release-note.html#%D9%86%D8%B3%D8%AE%D9%87-%DB%B3%DB%B2%DB%B1---%DB%B1%DB%B3%DB%B9%DB%B9%DB%B0%DB%B2%DB%B3%DB%B1">۳.۲.۱</a> حل شده است.</p>
